type Query{
    branches(
        branchId:Int
        search:String
        sort:Sort
        sortOption:SortOption
    ):[Branches!]!
}

type Branches{
    branchId:String!
    branchName:String!
    branchAddress:String!
    addedFrom:Int!
    register_in:String!
}

type Mutation{
    addBranch(
        branchName:String! 
        branchAddress:String!
    ): MutationResponse!

    updateBranch(
        branchId:Int!
        branchName:String
        branchAddress:String
    ): MutationResponse!

    deleteBranch(
        branchId:Int!
    ): MutationResponse!
}