type Query{
    user:User!
    users(
        userId:Int
        search:String
        sort:Sort
        sortOption:SortOption
    ):[User!]!
}

type User{
    userId:Int!
    username: String!
    birthDate: String
    gender:String!
    register_in: String!
}

type Mutation{
    login(input: login!) : UserResponce!
    register(input:register!) : UserResponce!
}

type UserResponce{
    status: Int!
    message: String!
    token: String
}

input login{
    username:String! 
    password:String!
}

input register{
    username:String!
    password:String!,
    repeatPassword:String!
    gender: gender!
    birthDate: String
    branchId: Int!
}

enum gender{
    male,
    female,
}