type Query{
    myPermisions:[Permission!]!
    allPermissions(
        userId:Int
        branchId:Int
        branchName:String
        userName:String
        sort:SortPerm
        sortOption:SortOption
    ): [Permission!]!
}

enum SortPerm{
    userName
    branchName
    createdAt
}


type Permission{
    upId:Int!
    branchId:Int!
    branchName:String!
    userId:Int!
    userName:String!
    permission:String!
    permissionModule:String!
    addedFromId:Int!
    addedFromName:String!
    createdAt:String!
}

type Mutation{
    addPermission(
        userId: Int!,
        branchId: Int!,
        permissionModule: PermissionModule!,
        permission: PermissionEnum!
    ): MutationResponse!
    
    deletePermission(
        up_id:Int!
    ): MutationResponse!
}

enum PermissionModule{
    Transports,
    Branches,
    Permissions
}

enum PermissionEnum{
    Create,
    Read,
    Update,
    Delete
}