type Mutation{
    addTransport(
        # transportName:String!
        transportImg:Upload!
        # branchId: Int!
        # transportColor: String!
    ):MutationResponse!
    # changeTransport
    # deleteTransport
}